setwd("C:/Users/kate/Documents/datascience/coursera")
data<-read.table("household_power_consumption.txt", header=T, sep=";", col.names=c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), na.strings="?", nrows=100000)
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data$Time<-strptime(paste(data$Date,data$Time), format="%Y-%m-%d %H:%M:%S")
data<-subset(data, data$Date>as.Date("2007-01-31"))
data<-subset(data, data$Date<as.Date("2007-02-03"))
png(file="plot3.png")
plot3<-plot(data$Time, data$Sub_metering_1, type="S", xlab="", ylab="Energy sub metering")
lines(data$Time, data$Sub_metering_2, col="red")
lines(data$Time, data$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()